server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: server-config
  cloud:
    config:
      name: server-config
      server:
        native:
          search-locations: classpath:/config-repo/